[package]
name = "miniverse"
version = "0.1.0"
edition = "2021"
author = "Sebastian Dominguez (joburg1035@yahoo.com)"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.7.0" }
rand = "0.8.5"
rand_distr = "0.4.3"
